"""
Report generation utilities.
"""

from pathlib import Path

from .models import ComparisonResult, SequenceRecord
from .mutation import mutation_summary


def generate_text_report(
    reference: SequenceRecord,
    query: SequenceRecord,
    result: ComparisonResult,
    output_file: str,
) -> None:
    """
    Generate a text report for sequence comparison.
    """

    path = Path(output_file)

    with path.open("w", encoding="utf-8") as report:

        report.write("=" * 60 + "\n")
        report.write("Sequence Comparison Report\n")
        report.write("=" * 60 + "\n\n")

        report.write(f"Reference : {reference.identifier}\n")
        report.write(f"Query     : {query.identifier}\n\n")

        report.write(f"Length    : {reference.length}\n")
        report.write(f"Matches   : {result.matches}\n")
        report.write(f"Mismatches: {result.mismatches}\n")
        report.write(f"Identity  : {result.identity}%\n\n")

        report.write("Mutation Summary\n")
        report.write("-" * 40 + "\n")

        if result.mismatches_list:
            for mutation in mutation_summary(result):
                report.write(mutation + "\n")
        else:
            report.write("No mutations found.\n")

        report.write("\nGenerated by Sequence Comparator\n")